### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by yads**
Fix security vulnerability https://github.com/mongoid/mongoid_search/security/dependabot/1

### CODE REVIEW

**Comment by dblock** [comment]
Want to finish the CI/CD started in https://github.com/mongoid/mongoid_search/pull/143 first?

**Comment by yads** [comment]
Good idea, there's more work that's needed on this PR anyway, but I'll pull the CI stuff in from that PR

**Comment by dblock** [comment]
@yads Tests are still failing, lmk if you need help.

**Comment by yads** [comment]
@dblock I think I've got it going now, is there an automated way to generate the changelog entry?

**Comment by dblock** [comment]
> @dblock I think I've got it going now, is there an automated way to generate the changelog entry?

Not today. Add a line saying something like "Replaced Travis-CI with GHA"?

**Pull request merged**
