### PR TITLE
Configurable strips

### LINKED ISSUE #106: Config search to not ignore dots
I have field with ip address like '10.0.10.0' and Mongoid::Search create one keyword only '10'. How to tune search to ignore dots ?

### PR DESCRIPTION
**Pull request by sveredyuk**
Fixed #106

### CODE REVIEW

**Comment by sveredyuk** [comment]
Hi, @dblock any chance to fix CI ?

**Comment by dblock** [comment]
I'm really not actively involved in this project, I just brought it into the mongoid org. But if nobody steps up I could help out maybe. Would appreciate some PRs and happy to look and merge for trivial things like CI of course.

**Comment by sveredyuk** [comment]
@dblock Thx

**Comment by rtrv** [comment]
@sveredyuk check out Travis result. Your last commit "Sort filtered keys" damages functionality. And I suppose it's out of "configurable strips" feature scope. Without that change all tests are passing well

**Comment by sveredyuk** [comment]
@rtrv Hm... ok. I'll try to revert it

**Comment by Mohakjuneja** [comment]
@sveredyuk I have an abbreviation field in my search criteria. However, an abbreviation such as B.E. is saved as two different keywords 'B' and 'E'. How can I ignore the dots while creating keywords for this field using configurable strips?

**Comment by sveredyuk** [comment]
@ Mohakjuneja You need one keyword like "BE" ?

**Comment by rtrv** [comment]
@Mohakjuneja here is the default configuration for gem initialization:
```
config.strip_symbols = /[._:;'\"`,?|+={}()!@#%^&*<>~\$\-\\\/\[\]]/
```
You can just remove the dot out of the regex:
```
config.strip_symbols = /[_:;'\"`,?|+={}()!@#%^&*<>~\$\-\\\/\[\]]/
```
Then you'll be able to search for "B.E." including dots and from the string `Example string.` the following keywords will be extracted: `example` and `string.` with a dot. If you want to search for `BE`, change `config.strip_accents` from the default:
```
config.strip_accents = /[^\s\p{Alnum}]/
```
To the following, adding the dot:
```
config.strip_accents = /[.^\s\p{Alnum}]/
```

**Comment by Mohakjuneja** [comment]
Thank you so much! That works!

**Comment by rgaufman** [comment]
Any suggestion how to change the above to correctly index MAC addresses and IP addresses?

**Comment by rgaufman** [comment]
Ah, this does what I want:

```ruby
    config.strip_symbols = /[_;'\"`,?|+={}()!@#%^&*<>~\$\-\\\/\[\]]/
    config.strip_accents = /[^\s\p{Alnum}.:]/
```

**Pull request merged**
