### PR TITLE
Multiple searches

### PR DESCRIPTION
**Pull request by pacop**
Hi,
I have added suport to have different searches with different criterias. I think it could be very useful, for instance let us imagine an example where we have two different searches for bands. One for author and another one for drummer. In this specific case, there are people who are both author and drummer, but in each search we only have the results for the specific position and not for both. That result was impossible to achieve, but now it is not.

Let me know if I should do sth else.

Thanks.

### CODE REVIEW

**Comment by pacop** [comment]
I have excluded spec directory from metric/blocks length to fix the problem with rubocop.

**Comment by dblock** [comment]
For rubocop run `rubocop -a ; rubocop --auto-gen-config` instead.

**Comment by pacop** [comment]
I have updated the last commit disabling MetricsLength for everything, since I don't see the benefits of continue increasing the max length in rubocop_todo.yml.
Example of running rubocop --auto-gen-config
```
@@ -31,7 +31,7 @@ Metrics/AbcSize:
 # Offense count: 3
 # Configuration parameters: CountComments, ExcludedMethods.
 Metrics/BlockLength:
-  Max: 271
+  Max: 28
```

Please, let me know if I should add something else. Thanks.

**Comment by dblock** [comment]
@pacop please rebase this, it needs to be green/mergeable.

**Comment by pacop** [comment]
@dblock It's done

**Comment by dblock** [comment]
^ @sveredyuk all yours, I was just cheerleading a bit

**Comment by sveredyuk** [comment]
@dblock Ok, let me check

**Comment by dblock** [comment]
@sveredyuk Aren't you a co-maintainer here? Go ahead and merge. I dropped in from the parent mongoid org, but have no intention to stay :)

**Comment by rtrv** [comment]
@pacop thanks! Might be useful for our gem usage too. Could you also increase the gem version to `0.3.6`? So I'll be able to push these changes into RubyGems with increased version while 0.4 is still in progress (sorry that it's so outdated, have been busy last time)

**Comment by pacop** [comment]
@rtrv it's done

**Comment by rtrv** [comment]
@pacop 0.3.6 has been pushed to RubyGems

**Pull request merged**
